/* Nuevo estado para la Orden de Compra */
INSERT INTO status_document_types (STATUS_DOCUMENT_TYPE_NAME, STATUS_DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_ID, NOTES, EDIT_MODE, STATUS_ORDER)
     VALUES ('Ajuste en aprobación','J',1,'Orden de Compra por confirmar con diferencias entre cantidad recibida y cantidad solicitada', 1, 4);
GO

/* Definición de rangos y % de validación para la diferencia de cantidad solicitada vrs cantidad recibida */
CREATE TABLE PURCHASE_ORDER_APPROVAL_RANGES
(
    PURCHASE_ORDER_APPROVAL_RANGE_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PURCHASE_ORDER_APPROVAL_RANGES PRIMARY KEY,
    REQUESTED_QUANTITY_FROM INT NOT NULL,
    REQUESTED_QUANTITY_TO INT NOT NULL,
    ALLOWED_DIFFERENCE_PERCENT DECIMAL(5,2) NOT NULL,
    IS_ACTIVE BIT NOT NULL DEFAULT(1),
    CREATED_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
    CREATED_BY_EMPLOYEE_ID INT NULL
);
GO

ALTER TABLE PURCHASE_ORDER_APPROVAL_RANGES ADD CONSTRAINT FK_PO_APPROVAL_RANGE_EMPLOYEE FOREIGN KEY (CREATED_BY_EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
GO

CREATE INDEX IX_PO_APPROVAL_RANGE_ACTIVE ON PURCHASE_ORDER_APPROVAL_RANGES (IS_ACTIVE, REQUESTED_QUANTITY_FROM, REQUESTED_QUANTITY_TO);
GO

/* Simpre debe haber un rango de 0 o de menor a mayor */
ALTER TABLE PURCHASE_ORDER_APPROVAL_RANGES ADD CONSTRAINT CK_POAR_QUANTITY_RANGE CHECK (REQUESTED_QUANTITY_FROM <= REQUESTED_QUANTITY_TO);
/* El porcentaje de validacion siempre debe ser positivo */
ALTER TABLE PURCHASE_ORDER_APPROVAL_RANGES ADD CONSTRAINT CK_POAR_PERCENT CHECK (ALLOWED_DIFFERENCE_PERCENT > 0 AND ALLOWED_DIFFERENCE_PERCENT <= 100);
GO

/* Se debe validar que no haya superposicion entre rangos activos del tipo (0 - 500), (10 - 600) o (100 - 400) */
CREATE TRIGGER TR_PURCHASE_ORDER_APPROVAL_RANGES_VALIDATE
			ON PURCHASE_ORDER_APPROVAL_RANGES 
			   AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS
    (SELECT 1
       FROM PURCHASE_ORDER_APPROVAL_RANGES A
      INNER JOIN inserted I ON A.PURCHASE_ORDER_APPROVAL_RANGE_ID <> I.PURCHASE_ORDER_APPROVAL_RANGE_ID
						   AND A.IS_ACTIVE = 1
						   AND I.IS_ACTIVE = 1
						   AND I.REQUESTED_QUANTITY_FROM <= A.REQUESTED_QUANTITY_TO
						   AND I.REQUESTED_QUANTITY_TO >= A.REQUESTED_QUANTITY_FROM)
    BEGIN
        RAISERROR ('Existen rangos activos superpuestos.', 16, 1);
		ROLLBACK TRANSACTION;
        RETURN;
    END
END
GO

/* se debe loguear cualquier modificación ya que esta implica una alteración de la regla de negocio para la aprobación de confirmación de ordenes de compra */
CREATE TABLE PURCHASE_ORDER_APPROVAL_RANGE_LOG
(
    PURCHASE_ORDER_APPROVAL_RANGE_LOG_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PURCHASE_ORDER_APPROVAL_RANGE_LOG PRIMARY KEY, 
    PURCHASE_ORDER_APPROVAL_RANGE_ID INT NOT NULL,
    PREVIOUS_REQUESTED_QUANTITY_FROM INT NOT NULL,
    PREVIOUS_REQUESTED_QUANTITY_TO INT NOT NULL,
    PREVIOUS_ALLOWED_DIFFERENCE_PERCENT DECIMAL(5,2) NOT NULL,
    PREVIOUS_IS_ACTIVE BIT NOT NULL,
    CHANGE_REASON NVARCHAR(1000) NOT NULL,
    CHANGED_BY_EMPLOYEE_ID INT NOT NULL,
    CHANGED_DATE DATETIME NOT NULL DEFAULT(GETDATE())    
);
GO

ALTER TABLE PURCHASE_ORDER_APPROVAL_RANGE_LOG ADD CONSTRAINT FK_PO_APPROVAL_RANGE_LOG_EMPLOYEE FOREIGN KEY (CHANGED_BY_EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
GO

CREATE INDEX IX_PO_APPROVAL_RANGE_LOG_RANGE ON PURCHASE_ORDER_APPROVAL_RANGE_LOG (PURCHASE_ORDER_APPROVAL_RANGE_ID);
GO

/* nuevo rol para las aprobaciones de los ajustes */
INSERT INTO [dbo].[AspNetRoles] (Id, ConcurrencyStamp, Name, NormalizedName)
     VALUES (NEWID(), NEWID(), 'Aprobación de ajustes en órdenes de compra','APROBACIÓN DE AJUSTES EN ÓRDENES DE COMPRA')
GO

/* se debe loguear quen Confirma o Devuelve una OC en estado de Ajuste en aprobación y elmotivo por el cual fue Deveuelta o Confirmada */
CREATE TABLE PURCHASE_ORDER_ADJUSTMENT_LOG
(
    PURCHASE_ORDER_ADJUSTMENT_LOG_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PURCHASE_ORDER_ADJUSTMENT_LOG PRIMARY KEY,
    PURCHASE_ORDER_ID INT NOT NULL,
    NEW_STATUS_DOCUMENT_TYPE_ID SMALLINT NOT NULL,
    REASON NVARCHAR(1000) NOT NULL,
    EMPLOYE_ID INT NOT NULL,
    CREATED_DATE DATETIME NOT NULL CONSTRAINT DF_PO_ADJ_LOG_CREATED_DATE DEFAULT(GETDATE())
);
GO

ALTER TABLE PURCHASE_ORDER_ADJUSTMENT_LOG ADD CONSTRAINT FK_PO_ADJ_LOG_PURCHASE_ORDER FOREIGN KEY (PURCHASE_ORDER_ID) REFERENCES PURCHASE_ORDERS(PURCHASE_ORDER_ID);
GO

ALTER TABLE PURCHASE_ORDER_ADJUSTMENT_LOG ADD CONSTRAINT FK_PO_ADJ_LOG_NEW_STATUS FOREIGN KEY (NEW_STATUS_DOCUMENT_TYPE_ID) REFERENCES STATUS_DOCUMENT_TYPES(STATUS_DOCUMENT_TYPE_ID);
GO

ALTER TABLE PURCHASE_ORDER_ADJUSTMENT_LOG ADD CONSTRAINT FK_PO_ADJ_LOG_EMPLOYEE FOREIGN KEY (EMPLOYE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
GO

CREATE INDEX IX_PO_ADJ_LOG_PURCHASE_ORDER ON PURCHASE_ORDER_ADJUSTMENT_LOG (PURCHASE_ORDER_ID);
GO

/* se requiere un motivo para almacenar el log de quien realizo el intento de confirmacion, que paso a Solicitud de aprobacion de ajustes la Orden de Compra */
INSERT INTO [dbo].[modification_reasons] (MODIFICATION_REASON_NAME, DOCUMENT_TYPE_ID, NOTES)
     VALUES ('Solicitud aprobación ajustes',1,'Se modifica debido a diferencias entre cantidad solicitada y cantidad recibida')
GO

/* nuevo rol para la configuracion de los rangos de validacion del % */
INSERT INTO [dbo].[AspNetRoles] (Id, ConcurrencyStamp, Name, NormalizedName)
     VALUES (NEWID(), NEWID(), 'Administración de tolerancias de ajustes en órdenes de compra','ADMINISTRACIÓN DE TOLERANCIAS DE AJUSTES EN ÓRDENES DE COMPRA')
GO

/* Definicion de preferencias de los usuarios, inicialmente parametriza las notificaciones de windows en el explorador */
CREATE TABLE employee_preferences
(
   EMPLOYEE_ID INT NOT NULL CONSTRAINT PK_EMPLOYEE_PREFERENCE PRIMARY KEY,
   ENABLE_NOTIFICATIONS BIT NOT NULL CONSTRAINT DF_EMPLOYEE_PREFERENCES_ENABLE_NOTIFICATION DEFAULT 0,
   CREATED_DATE DATETIME NOT NULL CONSTRAINT DF_EMPLOYEE_PREFERENCE_CREATED_DATE DEFAULT GETDATE(),
   UPDATED_DATE DATETIME NOT NULL CONSTRAINT DF_EMPLOYEE_PREFERENCE_UPDATED_DATE DEFAULT GETDATE(),
   CONSTRAINT FK_EMPLOYEE_PREFERENCE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES employees(EMPLOYEE_ID)
)
GO

/* Define las notificaciones que se van a aplicar para mostrar en el explorador como notificacion de windows */
CREATE TABLE notification_definitions
(
   NOTIFICATION_DEFINITION_ID INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_NOTIFICATION_DEFINITION PRIMARY KEY,
   NAME NVARCHAR(100) NOT NULL,
   DESCRIPTION NVARCHAR(250) NOT NULL,
   VALIDATION_INTERVAL_MINUTES INT NOT NULL,
   VALIDATION_QUERY NVARCHAR(MAX) NOT NULL,
   QUERY_PARAMETERS NVARCHAR(MAX) NULL,
   NOTIFICATION_MESSAGE NVARCHAR(250) NOT NULL,
   IS_ACTIVE BIT NOT NULL CONSTRAINT DF_NOTIFICATION_DEFINITION_IS_ACTIVE DEFAULT 0,
   CREATED_DATE DATETIME NOT NULL CONSTRAINT DF_NOTIFICATION_DEFINITION_CREATED_DATE DEFAULT GETDATE(),
   UPDATED_DATE DATETIME NOT NULL CONSTRAINT DF_NOTIFICATION_DEFINITION_UPDATED_DATE DEFAULT GETDATE(),
   LAST_VALIDATION_DATE DATETIME NULL
)
GO

/* Define que roles deben ver que notificaciones de windows */
CREATE TABLE notification_definition_roles
(
   NOTIFICATION_DEFINITION_ROLE_ID INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_NOTIFICATION_DEFINITION_ROLE PRIMARY KEY,
   NOTIFICATION_DEFINITION_ID INT NOT NULL CONSTRAINT FK_NDR_NOTIFICATION_DEFINITION FOREIGN KEY REFERENCES notification_definitions(NOTIFICATION_DEFINITION_ID),
   ROLE_ID NVARCHAR(450) NOT NULL CONSTRAINT FK_NDR_ROLE FOREIGN KEY REFERENCES AspNetRoles(ID),
   CONSTRAINT UQ_NOTIFICATION_DEFINITION_ROLE UNIQUE (NOTIFICATION_DEFINITION_ID, ROLE_ID)
)
GO

INSERT INTO NOTIFICATION_DEFINITIONS(NAME, DESCRIPTION, VALIDATION_INTERVAL_MINUTES, VALIDATION_QUERY, QUERY_PARAMETERS, NOTIFICATION_MESSAGE, IS_ACTIVE, CREATED_DATE, UPDATED_DATE)
VALUES('Aprobaciones pendientes de O.C.', 'Órdenes de compra pendientes de aprobación', 5, '<VALIDATION_QUERY>', NULL, 'Existen órdenes de compra pendientes de aprobación.', 1, GETDATE(), GETDATE())
GO

DECLARE @NOTIFICATION_DEFINITION_ID INT
DECLARE @APPROVE_ROLE_ID NVARCHAR(450)

SELECT @APPROVE_ROLE_ID = ID FROM AspNetRoles WHERE  Name = 'Aprobación de ajustes en órdenes de compra'
SELECT @NOTIFICATION_DEFINITION_ID = NOTIFICATION_DEFINITION_ID FROM notification_definitions WHERE  NAME = 'Aprobaciones pendientes de O.C.'

INSERT INTO notification_definition_roles (NOTIFICATION_DEFINITION_ID, ROLE_ID)
VALUES (@NOTIFICATION_DEFINITION_ID, @APPROVE_ROLE_ID)
GO