CREATE TABLE automatic_in_process
(
	AUTOMATIC_IN_PROCESS_ID INT NOT NULL IDENtITY(1,1) CONSTRAINT PK_AUTOMATIC_IN_PROCESS PRIMARY KEY,
	CREATION_DATE DATETIME NOT NULL CONSTRAINT DF_AUTOMATIC_IN_PROCESS_CREATION_DATE DEFAULT GETDATE(),
	PURCHASE_ORDER_ID INT NOT NULL 
)
GO

CREATE TABLE automatic_in_process_orders
(
	AUTOMATIC_IN_PROCESS_ORDER_ID INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_AUTOMATIC_IN_PROCESS_ORDER PRIMARY KEY,
	AUTOMATIC_IN_PROCESS_ID INT NOT NULL CONSTRAINT FK_AUTOMATIC_IN_PROCESS_ORDERS_AUTOMATIC_IN_PROCESS FOREIGN KEY REFERENCES AUTOMATIC_IN_PROCESS (AUTOMATIC_IN_PROCESS_ID),
	CUSTOMER_ORDER_IN_PROCESS_ID INT NOT NULL,
	CUSTOMER_ORDER_ID INT NOT NULL	
)
GO

CREATE TABLE automatic_in_process_detail
(
	AUTOMATIC_IN_PROCESS_DETAIL_ID INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_AUTOMATIC_IN_PROCESS_DETAIL PRIMARY KEY,
	AUTOMATIC_IN_PROCESS_ORDER_ID INT NOT NULL CONSTRAINT FK_AUTOMATIC_IN_PROCESS_DETAIL_AUTOMATIC_IN_PROCESS_ORDER FOREIGN KEY REFERENCES AUTOMATIC_IN_PROCESS_ORDERS (AUTOMATIC_IN_PROCESS_ORDER_ID),
	CUSTOMER_ORDER_IN_PROCESS_DETAIL_ID	INT NOT NULL,
	CUSTOMER_ORDER_DETAIL_ID INT NOT NULL,	
	REFERENCE_ID INT NOT NULL CONSTRAINT FK_automatic_in_process_detail_REFERENCE FOREIGN KEY REFERENCES ITEM_REFERENCES (REFERENCE_ID),
	WAREHOUSE_ID SMALLINT NOT NULL CONSTRAINT FK_automatic_in_process_detail_WAREHOUSE FOREIGN KEY REFERENCES WAREHOUSES (WAREHOUSE_ID),	
	ASSIGNED_QUANTITY INT NOT NULL,	
	BRAND VARCHAR(250)
)
GO

CREATE TABLE visualized_automatic_in_process
(
	AUTOMATIC_IN_PROCESS_ID INT NOT NULL CONSTRAINT FK_VISUALIZED_AUTOMATIC_IN_PROCESS_AUTOMATIC_IN_PROCESS FOREIGN KEY REFERENCES AUTOMATIC_IN_PROCESS (AUTOMATIC_IN_PROCESS_ID),
	EMPLOYEE_ID INT NOT NULL CONSTRAINT FK_VISUALIZED_AUTOMATIC_IN_PROCESS_EMPLOYEE FOREIGN KEY REFERENCES EMPLOYEES (EMPLOYEE_ID),
	VISUALIZED_DATE DATETIME NOT NULL CONSTRAINT DF_VISUALIZED_AUTOMATIC_IN_PROCESS_VISUALIZED_DATE DEFAULT GETDATE(),
	CONSTRAINT PK_VISUALIZED_AUTOMATIC_IN_PROCESS PRIMARY KEY (AUTOMATIC_IN_PROCESS_ID, EMPLOYEE_ID)
)
GO
