CREATE OR ALTER PROCEDURE SP_GET_CONFIRMED_PURCHASES_WITH_AUTOMATIC_ASSIGMENT
	@EmployeeId INT = NULL,
	@SearchKey VARCHAR(MAX) = NULL
AS
BEGIN
	SELECT a.AUTOMATIC_IN_PROCESS_ID, a.PURCHASE_ORDER_ID, b.ORDER_NUMBER, c.IDENTITY_NUMBER, c.PROVIDER_NAME, b.PROFORMA_NUMBER,
		   b.IMPORT_NUMBER, b.REAL_RECEIPT_DATE, CAST (a.Creation_Date AS date) CREATION_DATE
	  FROM automatic_in_process a
	  JOIN purchase_orders b ON b.PURCHASE_ORDER_ID = a.PURCHASE_ORDER_ID
	  JOIN providers c ON c.PROVIDER_ID = b.PROVIDER_ID	  
	 WHERE NOT EXISTS (SELECT 1 
						 FROM visualized_automatic_in_process va 
						WHERE va.AUTOMATIC_IN_PROCESS_ID = a.AUTOMATIC_IN_PROCESS_ID
						  AND (va.EMPLOYEE_ID = @EmployeeId or @EmployeeId IS NULL)) 
	   AND (@SearchKey IS NULL 
	    OR b.ORDER_NUMBER LIKE '%'+@SearchKey+'%'
		OR c.IDENTITY_NUMBER LIKE '%'+@SearchKey+'%'
		OR c.PROVIDER_NAME LIKE '%'+@SearchKey+'%'
		OR b.PROFORMA_NUMBER LIKE '%'+@SearchKey+'%'
		OR b.IMPORT_NUMBER LIKE '%'+@SearchKey+'%'
		OR REPLACE(CONVERT(VARCHAR(10), b.REAL_RECEIPT_DATE, 111),'/','\') LIKE '%'+@SearchKey+'%'
		OR REPLACE(CONVERT(VARCHAR(10), CAST (a.Creation_Date AS date), 111),'/','\') LIKE '%'+@SearchKey+'%')
END
GO


