CREATE OR ALTER PROCEDURE SP_GET_CUSTOMER_ORDERS_WITH_AUTOMATIC_ASSIGMENT
	@ProcessId INT = NULL
AS
BEGIN
	SELECT a.AUTOMATIC_IN_PROCESS_ORDER_ID, b.CUSTOMER_ORDER_ID, b.ORDER_NUMBER, C.IDENTITY_NUMBER, c.CUSTOMER_NAME, b.ORDER_DATE, b.ESTIMATED_DELIVERY_DATE, d.STATUS_DOCUMENT_TYPE_NAME
	  FROM automatic_in_process_orders a
	  JOIN customer_orders b ON b.CUSTOMER_ORDER_ID = a.CUSTOMER_ORDER_ID
	  JOIN customers c ON c.CUSTOMER_ID = b.CUSTOMER_ID 
	  JOIN status_document_types d ON d.STATUS_DOCUMENT_TYPE_ID = b.STATUS_DOCUMENT_TYPE_ID	  
	 WHERE AUTOMATIC_IN_PROCESS_ID = @ProcessId
END
GO