CREATE OR ALTER TRIGGER Trg_Confirm_Purchase_Order
   ON  purchase_orders AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	IF UPDATE(STATUS_DOCUMENT_TYPE_ID)
		IF (SELECT STATUS_DOCUMENT_TYPE_ID FROM INSERTED) = 2 AND (SELECT STATUS_DOCUMENT_TYPE_ID FROM DELETED) = 1
		BEGIN
			DECLARE @PurchaseOrderId INT = (SELECT PURCHASE_ORDER_ID FROM INSERTED)

			EXEC SP_Gen_Orders_In_Proc_From_Confirmed_Purchase_Order @PurchaseOrderId 
		END	
END
GO
