CREATE TABLE Inventory_Automation_Connections(
	INVENTORY_AUTOMATION_CONNECTION_ID INT NOT NULL IDENTITY (1,1) CONSTRAINT PK_Inventory_Automation_Connections PRIMARY KEY,
	SERVER_NAME VARCHAR(256) NOT NULL,
	PORT_NUMBER VARCHAR(10) NULL,
	[DATABASE_NAME] VARCHAR(100) NOT NULL,
	[USER_ID] VARCHAR(50) NOT NULL,
	[PASSWORD] VARCHAR(20) NOT NULL,
	ACTIVE BIT NOT NULL CONSTRAINT DF_Inventory_Automation_Connections_Active DEFAULT (0)) 