CREATE TABLE FTP_Writing_Connections(
	FTP_WRITING_CONNECTION_ID INT NOT NULL IDENTITY (1,1) CONSTRAINT PK_FTP_Writing_Connections PRIMARY KEY,
	[HOST_NAME] VARCHAR(256) NOT NULL,
	PORT_NUMBER VARCHAR(10) NULL,
	[USER_NAME] VARCHAR(50) NOT NULL,
	[PASSWORD] VARCHAR(50) NOT NULL,
	CRONO_EXP VARCHAR(30) NOT NULL,
	REWRITE_FILE BIT NOT NULL DEFAULT 1, 
	ACTIVE BIT NOT NULL CONSTRAINT DF_FTP_Writing_Connections_Active DEFAULT (0)) 