CREATE TABLE local_warehouse_alarms
(
	LOCAL_WAREHOUSE_ALARM_ID INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_LOCAL_WAREHOUSE_ALARM PRIMARY KEY,
	DOCUMENT_TYPE_ID SMALLINT NOT NULL CONSTRAINT FK_LOCAL_WAREHOUSE_ALARM_DOCUMENT_TYPE REFERENCES DOCUMENT_TYPES (DOCUMENT_TYPE_ID),
	DOCUMENT_NUMBER INT NOT NULL,
	REFERENCE_LIST NVARCHAR(MAX) NOT NULL,
	CUSTOMER_ORDER_LIST NVARCHAR(MAX),
	ALARM_DATE DATETIME NOT NULL
)
GO

CREATE TABLE visualized_local_warehouse_alarms
(
	LOCAL_WAREHOUSE_ALARM_ID INT NOT NULL CONSTRAINT FK_VISUALIZED_LOCAL_WAREHOUSE_ALARM_LOCAL_WAREHOUSE_ALARM REFERENCES LOCAL_WAREHOUSE_ALARMS (LOCAL_WAREHOUSE_ALARM_ID),
	EMPLOYEE_ID INT NOT NULL CONSTRAINT FK_LOCAL_WAREHOUSE_ALARM_EMPLOYEE REFERENCES EMPLOYEES (EMPLOYEE_ID),
	VISUALIZED_DATE DATETIME NOT NULL CONSTRAINT DF_VISUALIZED_LOCAL_WAREHOUSE_ALARMS DEFAULT GETDATE(),
	CONSTRAINT PK_VISUALIZED_LOCAL_WAREHOUSE_ALARM PRIMARY KEY (LOCAL_WAREHOUSE_ALARM_ID, VISUALIZED_DATE)
)
GO

INSERT INTO AspNetRoles
	 VALUES('65473851-4B73-4A81-B9CB-0DF2BD97F0AA', '7A64AD2C-9AE6-4417-827E-85D2EDCAFA5E', 'Consulta de notificaciones por ingreso de mercancía a bodega local', 'CONSULTA DE NOTIFICACIONES POR INGRESO DE MERCANCÍA A BODEGA LOCAL')
GO