USE Aldebaran
GO

IF EXISTS (SELECT 1 FROM sys.columns WHERE Name = 'PURCHASE_ORDER_VARIATION' AND object_id = OBJECT_ID('ITEM_REFERENCES')) 
	ALTER TABLE [item_references] DROP COLUMN PURCHASE_ORDER_VARIATION 
GO

ALTER TABLE [item_references] ADD PURCHASE_ORDER_VARIATION INT NOT NULL CONSTRAINT DF_PURCHASE_ORDER_VARIATION DEFAULT 0
GO

CREATE OR ALTER PROCEDURE SP_IS_VALID_PURCHASE_ORDER_VARIATION
	@PROVIDER_ID INT, 
	@REFERENCE_ID INT, 
	@PURCHASE_ORDER_ID INT = -1, 
	@IS_VALID_VARIATION BIT OUT
AS
BEGIN 
	DECLARE @Variation INT

	SET @IS_VALID_VARIATION = 0
	   
	SELECT @Variation = PURCHASE_ORDER_VARIATION FROM item_references WHERE REFERENCE_ID = @REFERENCE_ID
	
	/*No tiene configurada validacion de orden de compra*/
	if @Variation <= 0 
	BEGIN 
		SET @IS_VALID_VARIATION = 1
		RETURN 
	END
END 
GO